#!/usr/bin/env bash
#
# SETUP
# =====
#
# Aaron Greenberg
# April 22, 2013
#
# First time run-through?  Sets up your machine with some good OS X defaults
# and then installs some important dependencies using Homebrew.  Makes sure you
# have Homebrew, too.

. osx/set-defaults.sh

if test ! `which brew`
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit 1
else
  echo "  + Homebrew found."
fi

# Install Homebrew dependencies
brew tap aaronjgreenberg/homebrew-aaron
brew install coreutils git ffmpeg mongodb redis emacs aaron-grc

exit 0
